title: Shuvarthy Debnath
#logo: /assets/img/headshot_circle.png
[LinkedIn](https://www.linkedin.com/in/shuvarthyd/)
theme: jekyll-theme-minimal

url: 'https://shuvarthyd.github.io/' # your main domain
baseurl: 'portfolio/' # if you're using custom domain keep this blank example: baseurl: ''

