title: Shuvarthy Debnath
#logo: /assets/img/headshot_circle.png
#description: text below image
theme: jekyll-theme-minimal

url: 'https://shuvarthyd.github.io/' # your main domain
baseurl: 'portfolio/' # if you're using custom domain keep this blank example: baseurl: ''

